const CONFIG=window.WPU_CONFIG||{};let sb=null;try{if(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey&&!CONFIG.supabaseUrl.includes('YOUR-'))sb=supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey)}catch(e){}
let cloudReady=!!sb, currentUser=null;
async function cloudLoad(){if(!sb)return; try{const [w,e,r,d,i]=await Promise.all([sb.from('weekly_winners').select('*').order('created_at',{ascending:false}),sb.from('events').select('*').order('created_at',{ascending:false}),sb.from('results').select('*').order('created_at',{ascending:false}),sb.from('documents').select('*').order('created_at',{ascending:false}),sb.from('wpu_info').select('*').eq('id',1).single()]); if(!w.error)data.winners=w.data.map(x=>({id:x.id,week:x.week,race:x.race,name:x.name,club:x.club,date:x.date,image:x.image_url,caption:x.caption})); if(!e.error)data.events=e.data.map(x=>({id:x.id,title:x.title,date:x.date,location:x.location,description:x.description,images:x.images||[]})); if(!r.error)data.results=r.data.map(x=>({id:x.id,title:x.title,category:x.category,date:x.date,url:x.pdf_url})); if(!d.error)data.docs=d.data.map(x=>({id:x.id,title:x.title,type:x.type,date:x.date,url:x.url,note:x.note})); if(!i.error&&i.data)data.info={about:i.data.about||'',contacts:i.data.contacts||'',management:i.data.management||'',constitution:i.data.constitution||''}; }catch(e){console.warn('Cloud load failed',e)} }
async function cloudInsert(table,row){if(!sb)return null; const {data:res,error}=await sb.from(table).insert(row).select().single(); if(error)throw error; return res}
async function uploadMedia(file){
 if(!sb||!file)return null;
 const ext=(file.name.split('.').pop()||'bin').toLowerCase();
 const path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;
 const contentType=file.type||({'pdf':'application/pdf','jpg':'image/jpeg','jpeg':'image/jpeg','png':'image/png','webp':'image/webp'}[ext]||'application/octet-stream');
 const {error}=await sb.storage.from('wpu-media').upload(path,file,{upsert:false,contentType,cacheControl:'3600'});
 if(error)throw error;
 return sb.storage.from('wpu-media').getPublicUrl(path).data.publicUrl;
}
function fileData(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function loginAdmin(){if(!sb){alert('Cloud is not configured.');return} const email=val('ae'),password=val('ap');const {data:res,error}=await sb.auth.signInWithPassword({email,password});if(error){alert(error.message);return}currentUser=res.user;await cloudLoad();alert('Admin aangemeld.');render()}
async function logoutAdmin(){if(sb)await sb.auth.signOut();currentUser=null;render()}
const cats=['POTCH','KOSH','SNU','VRYSTAAT','JUNIORS','WPU'];
const seed={winners:[{id:'w1',week:'Week 1',race:'Voorbeeld Wedvlug',name:'Laai wenner in by Admin',club:'WPU',date:'2026-01-01',image:'',caption:'Weeklikse wenner'}],events:[{id:'e1',title:'Potjiekosdag 2026',date:'2026-01-01',location:'WPU',description:'Laai foto’s en besonderhede hier by Admin.',images:[]}],results:[],docs:[],info:{about:'Welkom by die Westelike Posduif Unie se 2026 digitale jaarboek.',contacts:'Kontakpersone kan hier deur die administrateur gelaai word.',constitution:'Laai die WPU Konstitusie as ’n PDF in die Admin-afdeling.'}};
let data=JSON.parse(localStorage.getItem('wpu_data')||'null')||seed;let page='home';let cat='ALL';
const save=()=>localStorage.setItem('wpu_data',JSON.stringify(data));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const imgOrLogo=(src,cls)=>src?`<img class="${cls}" src="${esc(src)}">`:`<img class="${cls} placeholder" src="assets/wpu-logo.jpg">`;
function nav(){const items=[['home','Tuis'],['winners','Weeklikse wenners'],['results','Uitslae'],['yearbook','Jaarboek 2026'],['events','Byeenkomste'],['info','WPU Inligting'],['admin','Admin']];document.querySelector('#nav').innerHTML=items.map(x=>`<button class="navbtn ${page===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}
function go(p){page=p;cat='ALL';render();scrollTo(0,0)}
function render(){nav();const a=document.querySelector('#app');({home:home,winners:winPage,results:resultsPage,yearbook:yearbook,events:eventsPage,info:infoPage,admin:adminPage}[page]||home)(a)}
function home(a){const ws=data.winners.slice(0,6);a.innerHTML=`<section class="hero"><img src="assets/wpu-logo.jpg"><div><h1>WPU 2026</h1><p>Jou digitale jaarboek, weeklikse wenners, uitslae en byeenkomste.</p></div></section><h2>🏆 Weeklikse wenners</h2><div class="grid">${ws.map(w=>winnerCard(w)).join('')||empty()}</div><h2>📊 Jongste uitslae</h2>${resultList(data.results.slice(0,5))}<h2>📅 Komende / onlangse byeenkomste</h2><div class="grid">${data.events.slice(0,4).map(eventCard).join('')||empty()}</div>`}
function winnerCard(w){return `<article class="card winner-card">${imgOrLogo(w.image,'winner-img')}<div class="body"><div class="meta">${esc(w.week)} • ${esc(w.date)}</div><h3>${esc(w.race)}</h3><b>${esc(w.name)}</b><div class="meta">${esc(w.club)}</div><p>${esc(w.caption||'')}</p></div></article>`}
function winPage(a){a.innerHTML=`<h1>Weeklikse wenners</h1><p class="small">Die nuutste wenners kan hier eerste vertoon word wanneer die app oopmaak.</p><div class="grid">${data.winners.map(winnerCard).join('')||empty()}</div>`}
function chips(){return `<div class="chips"><button class="chip ${cat==='ALL'?'active':''}" onclick="filterCat('ALL')">Alles</button>${cats.map(c=>`<button class="chip ${cat===c?'active':''}" onclick="filterCat('${c}')">${c}</button>`).join('')}</div>`}
function filterCat(c){cat=c;render()}
function resultsPage(a){let rs=data.results.filter(r=>cat==='ALL'||r.category===cat);a.innerHTML=`<h1>Uitslae</h1>${chips()}${resultList(rs)||empty()}`}
function resultList(rs){return rs.length?rs.map(r=>`<div class="pdf"><div class="ico">📄</div><div><b>${esc(r.title)}</b><div class="meta">${esc(r.category)} • ${esc(r.date||'')}</div></div>${r.url?`<div class="actions"><button class="btn" type="button" onclick="openPdf(${JSON.stringify(r.url)},${JSON.stringify(r.title)})">Maak PDF oop</button><a class="btn secondary" href="${esc(r.url)}" target="_blank" rel="noopener">Open direk</a></div>`:''}</div>`).join(''):''}
function yearbook(a){let docs=data.docs.filter(d=>d.type==='yearbook');a.innerHTML=`<h1>Jaarboek 2026</h1>${docs.length?docs.map(docCard).join(''):empty('Laai die 2026 jaarboek in by Admin.')}`}
function docCard(d){return `<div class="pdf"><div class="ico">📘</div><div><b>${esc(d.title)}</b><div class="meta">${esc(d.date||'')} • ${esc(d.note||'')}</div></div>${d.url?`<button class="btn" type="button" onclick="openPdf(${JSON.stringify(d.url)},${JSON.stringify(d.title)})">Maak PDF oop</button>`:''}</div>`}
function eventsPage(a){a.innerHTML=`<h1>Byeenkomste & Funksies</h1><div class="grid">${data.events.map(eventCard).join('')||empty()}</div>`}
function eventCard(e){const imgs=e.images||[];return `<article class="card event-card">${imgs[0]?`<img class="event-img" src="${esc(imgs[0])}" onclick="viewEvent(${JSON.stringify(e.id)})" alt="">`:`<div class="event-img placeholder"></div>`}<div class="body"><div class="meta">${esc(e.date)}${e.location?' • '+esc(e.location):''}</div><h3>${esc(e.title)}</h3><p>${mapsHtml(e.description||'')}</p>${imgs.length>1?`<button class="btn secondary" type="button" onclick="viewEvent(${JSON.stringify(e.id)})">View ${imgs.length} foto’s</button>`:''}</div></article>`}
function mapsHtml(text){const raw=String(text||'');const urls=[];raw.replace(/https?:\/\/[^\s"'<>]+/gi,u=>{urls.push(u.replace(/[),.;]+$/,''));return u});let clean=raw.replace(/<iframe[\s\S]*?<\/iframe>/gi,'').replace(/<[^>]+>/g,'');clean=esc(clean).replace(/https?:\/\/[^\s<]+/gi,'');let links=[...new Set(urls)].map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener" class="maplink">📍 Maak kaart oop</a>`).join(' ');return (clean.trim()?clean+' ':'')+links}
function viewEvent(id){const e=data.events.find(x=>x.id===id);if(!e)return;const imgs=e.images||[];const old=document.getElementById('galleryModal');if(old)old.remove();const m=document.createElement('div');m.id='galleryModal';m.className='pdfmodal';m.innerHTML=`<div class="gallerybox"><div class="pdfhead"><b>${esc(e.title)}</b><button class="btn secondary" onclick="document.getElementById('galleryModal').remove()">Sluit</button></div><div class="gallerymain">${imgs[0]?`<img id="galleryMain" src="${esc(imgs[0])}">`:''}</div><div class="gallerythumbs">${imgs.map((u,i)=>`<img src="${esc(u)}" onclick="document.getElementById('galleryMain').src=${JSON.stringify(u)}" class="${i===0?'active':''}">`).join('')}</div></div>`;document.body.appendChild(m)}
function infoPage(a){a.innerHTML=`<h1>WPU Inligting</h1><div class="admin"><h3>Oor die WPU</h3><div class="info">${esc(data.info.about)}</div></div><div class="admin"><h3>Kontakpersone</h3><div class="info">${esc(data.info.contacts)}</div></div><div class="admin"><h3>Voorsitter / Dagbestuur / Amptenare</h3><div class="info">${esc(data.info.management||'')}</div></div><div class="admin"><h3>Konstitusie</h3><div class="info">${esc(data.info.constitution)}</div></div>${data.docs.filter(d=>d.type==='info').map(docCard).join('')}`}
function empty(t='Nog geen items gelaai nie.') {return `<div class="empty">${esc(t)}</div>`}
function adminPage(a){
if(sb&&!currentUser){a.innerHTML=`<h1>WPU Admin</h1><div class="admin"><h3>Admin-aanmelding</h3><div class="row"><div class="field"><label>E-pos</label><input id="ae" type="email"></div><div class="field"><label>Wagwoord</label><input id="ap" type="password"></div></div><div class="actions"><button class="btn" onclick="loginAdmin()">Meld aan</button></div></div><div class="notice">Cloud-modus is aktief. Slegs die aangewese admin-gebruiker behoort inhoud te kan verander.</div>`;return}
a.innerHTML=`<h1>WPU Admin</h1><div class="notice">${sb?`Cloud-modus: aangemeld as <b>${esc(currentUser?.email||'')}</b>.`:'Plaaslike demo-modus. Vir een gedeelde databasis vir almal, stel Supabase in volgens SETUP.md.'}</div><div class="actions"><button class="btn secondary" onclick="logoutAdmin()">Meld af</button></div>
<div class="admin"><h3>1. Weeklikse wenner</h3><div class="row"><div class="field"><label>Week</label><input id="ww"></div><div class="field"><label>Wedvlug</label><input id="wr"></div><div class="field"><label>Wenner</label><input id="wn"></div><div class="field"><label>Klub</label><input id="wc"></div><div class="field"><label>Datum</label><input id="wd" type="date"></div><div class="field"><label>Foto URL</label><input id="wi"></div><div class="field"><label>Foto lêer</label><input id="wif" type="file" accept="image/*"></div></div><div class="actions"><button class="btn" onclick="addWinner()">Voeg wenner by</button></div></div>
<div class="admin"><h3>2. Byeenkoms / funksie</h3><div class="row"><div class="field"><label>Naam</label><input id="et"></div><div class="field"><label>Datum</label><input id="ed" type="date"></div><div class="field"><label>Plek</label><input id="el"></div><div class="field"><label>Hooffoto URL</label><input id="ei"></div><div class="field"><label>Hooffoto lêer</label><input id="eif" type="file" accept="image/*"></div><div class="field"><label>Meer foto’s</label><input id="eifs" type="file" accept="image/*" multiple></div><div class="field"><label>Beskrywing / Google Maps skakel of embed</label><textarea id="ex" placeholder="Plak die Google Maps skakel of embed-kode hier in."></textarea></div></div><div class="actions"><button class="btn" onclick="addEvent()">Skep byeenkoms</button></div></div>
<div class="admin"><h3>3. Uitslag PDF / dokument</h3><div class="row"><div class="field"><label>Titel</label><input id="rt"></div><div class="field"><label>Seksie</label><select id="rc"><option>WPU</option>${cats.filter(x=>x!=='WPU').map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Datum</label><input id="rd" type="date"></div><div class="field"><label>PDF URL</label><input id="ru"></div><div class="field"><label>PDF lêer</label><input id="ruf" type="file" accept="application/pdf"></div></div><div class="actions"><button class="btn" onclick="addResult()">Voeg uitslag by</button></div></div>
<div class="admin"><h3>4. Jaarboek / WPU dokument</h3><div class="row"><div class="field"><label>Titel</label><input id="dt"></div><div class="field"><label>Tipe</label><select id="dy"><option value="yearbook">Jaarboek 2026</option><option value="info">WPU Inligting</option></select></div><div class="field"><label>PDF URL</label><input id="du"></div><div class="field"><label>PDF lêer</label><input id="duf" type="file" accept="application/pdf"></div><div class="field"><label>Nota</label><input id="dn"></div></div><div class="actions"><button class="btn" onclick="addDoc()">Voeg dokument by</button></div></div>
<div class="admin"><h3>5. WPU Inligting</h3><div class="field"><label>Oor WPU</label><textarea id="ia">${esc(data.info.about)}</textarea></div><div class="field"><label>Kontakpersone</label><textarea id="ic">${esc(data.info.contacts)}</textarea></div><div class="field"><label>Voorsitter / Dagbestuur / Amptenare</label><textarea id="im">${esc(data.info.management||'')}</textarea></div><div class="field"><label>Konstitusie beskrywing</label><textarea id="ix">${esc(data.info.constitution)}</textarea></div><div class="actions"><button class="btn" onclick="saveInfo()">Stoor WPU inligting</button></div></div>
<div class="admin"><h3>6. Rugsteun</h3><div class="actions"><button class="btn secondary" onclick="downloadBackup()">Laai rugsteun af</button><button class="btn secondary" onclick="document.getElementById('backup').click()">Laai rugsteun op</button><input id="backup" type="file" accept="application/json" hidden onchange="restoreBackup(event)"></div></div>
<div class="admin"><h3>7. Bestaande inhoud — Edit / Delete</h3>${adminItems()}</div>`}
function adminItems(){const item=(type,x,title,meta)=>`<div class="adminitem"><div><b>${esc(title)}</b><div class="small">${esc(meta||'')}</div></div><div class="actions"><button class="btn secondary" onclick="editItem('${type}','${x.id}')">Edit</button><button class="btn danger" onclick="deleteItem('${type}','${x.id}')">Delete</button></div></div>`;return [...data.events.map(x=>item('event',x,x.title,`Byeenkoms • ${x.date||''}`)),...data.winners.map(x=>item('winner',x,x.name,`${x.week} • ${x.race}`)),...data.results.map(x=>item('result',x,x.title,`${x.category} • ${x.date||''}`)),...data.docs.map(x=>item('doc',x,x.title,`${x.type} • ${x.date||''}`))].join('')||empty('Geen inhoud nie.')}
function editItem(type,id){const arr=type==='event'?data.events:type==='winner'?data.winners:type==='result'?data.results:data.docs;const x=arr.find(y=>y.id===id);if(!x)return; if(type==='event'){valSet('et',x.title);valSet('ed',x.date);valSet('el',x.location);valSet('ei',x.images?.[0]||'');valSet('ex',x.description);window._edit={type,id}}else if(type==='winner'){valSet('ww',x.week);valSet('wr',x.race);valSet('wn',x.name);valSet('wc',x.club);valSet('wd',x.date);valSet('wi',x.image);window._edit={type,id}}else if(type==='result'){valSet('rt',x.title);valSet('rc',x.category);valSet('rd',x.date);valSet('ru',x.url);window._edit={type,id}}else{valSet('dt',x.title);valSet('dy',x.type);valSet('du',x.url);valSet('dn',x.note);window._edit={type,id}}alert('Edit-vorm ingevul. Maak jou veranderinge en druk die knoppie.')}
function valSet(id,v){const el=document.getElementById(id);if(el)el.value=v||''}
async function deleteItem(type,id){if(!confirm('Is jy seker jy wil hierdie item verwyder?'))return;const table=type==='event'?'events':type==='winner'?'weekly_winners':type==='result'?'results':'documents';try{if(sb){const {error}=await sb.from(table).delete().eq('id',id);if(error)throw error}const arr=type==='event'?data.events:type==='winner'?data.winners:type==='result'?data.results:data.docs;const i=arr.findIndex(x=>x.id===id);if(i>=0)arr.splice(i,1);save();render()}catch(e){alert(e.message||e)}}
async function addWinner(){try{let image=val('wi');const f=document.getElementById('wif')?.files[0];if(f)image=sb?await uploadMedia(f):await fileData(f);const row={id:crypto.randomUUID(),week:val('ww'),race:val('wr'),name:val('wn'),club:val('wc'),date:val('wd'),image:image,caption:'Weeklikse wenner'};const ed=window._edit?.type==='winner'?window._edit:null;if(sb){if(ed){const {error}=await sb.from('weekly_winners').update({week:row.week,race:row.race,name:row.name,club:row.club,date:row.date||null,image_url:row.image}).eq('id',ed.id);if(error)throw error;row.id=ed.id}else{const x=await cloudInsert('weekly_winners',{week:row.week,race:row.race,name:row.name,club:row.club,date:row.date||null,image_url:row.image,caption:row.caption});row.id=x.id}}const i=data.winners.findIndex(x=>x.id===(ed?.id));if(ed&&i>=0)data.winners[i]=row;else data.winners.unshift(row);window._edit=null;save();render()}catch(e){alert(e.message||e)}}
async function addEvent(){try{let images=[];let main=val('ei');const mf=document.getElementById('eif')?.files[0];if(mf)main=sb?await uploadMedia(mf):await fileData(mf);if(main)images.push(main);for(const f of Array.from(document.getElementById('eifs')?.files||[])){images.push(sb?await uploadMedia(f):await fileData(f))}const oldEvent=window._edit?.type==='event'?data.events.find(x=>x.id===window._edit.id):null;if(oldEvent&&images.length===1&&!document.getElementById('eifs')?.files?.length)images=[images[0],...(oldEvent.images||[]).slice(1)];else if(oldEvent&&!images.length)images=oldEvent.images||[];const row={id:crypto.randomUUID(),title:val('et'),date:val('ed'),location:val('el'),description:val('ex'),images:images};const ed=window._edit?.type==='event'?window._edit:null;if(sb){if(ed){const {error}=await sb.from('events').update({title:row.title,date:row.date||null,location:row.location,description:row.description,images:row.images.length?row.images:data.events.find(x=>x.id===ed.id)?.images||[]}).eq('id',ed.id);if(error)throw error;row.id=ed.id;if(!row.images.length)row.images=data.events.find(x=>x.id===ed.id)?.images||[]}else{const x=await cloudInsert('events',{title:row.title,date:row.date||null,location:row.location,description:row.description,images:row.images});row.id=x.id}}else if(ed&&!row.images.length)row.images=data.events.find(x=>x.id===ed.id)?.images||[];const i=data.events.findIndex(x=>x.id===(ed?.id));if(ed&&i>=0)data.events[i]=row;else data.events.unshift(row);window._edit=null;save();render()}catch(e){alert(e.message||e)}}
async function addResult(){try{let url=val('ru');const f=document.getElementById('ruf')?.files[0];if(f)url=sb?await uploadMedia(f):await fileData(f);const row={id:crypto.randomUUID(),title:val('rt'),category:val('rc'),date:val('rd'),url:url};const ed=window._edit?.type==='result'?window._edit:null;if(sb){if(ed){const {error}=await sb.from('results').update({title:row.title,category:row.category,date:row.date||null,pdf_url:row.url}).eq('id',ed.id);if(error)throw error;row.id=ed.id}else{const x=await cloudInsert('results',{title:row.title,category:row.category,date:row.date||null,pdf_url:row.url});row.id=x.id}}const i=data.results.findIndex(x=>x.id===(ed?.id));if(ed&&i>=0)data.results[i]=row;else data.results.unshift(row);window._edit=null;save();render()}catch(e){alert(e.message||e)}}
async function addDoc(){try{let url=val('du');const f=document.getElementById('duf')?.files[0];if(f)url=sb?await uploadMedia(f):await fileData(f);const row={id:crypto.randomUUID(),title:val('dt'),type:val('dy'),date:new Date().toISOString().slice(0,10),url:url,note:val('dn')};const ed=window._edit?.type==='doc'?window._edit:null;if(sb){if(ed){const {error}=await sb.from('documents').update({title:row.title,type:row.type,url:row.url,note:row.note}).eq('id',ed.id);if(error)throw error;row.id=ed.id}else{const x=await cloudInsert('documents',{title:row.title,type:row.type,date:row.date,url:row.url,note:row.note});row.id=x.id}}const i=data.docs.findIndex(x=>x.id===(ed?.id));if(ed&&i>=0){row.date=data.docs[i].date;data.docs[i]=row}else data.docs.unshift(row);window._edit=null;save();render()}catch(e){alert(e.message||e)}}
async function saveInfo(){data.info={about:val('ia'),contacts:val('ic'),management:val('im'),constitution:val('ix')};if(sb){const {error}=await sb.from('wpu_info').upsert({id:1,...data.info,updated_at:new Date().toISOString()});if(error){alert(error.message);return}}save();render()}
function val(id){return document.getElementById(id)?.value?.trim()||''}
async function downloadBackup(){
 try{
  if(sb){await cloudLoad();}
  const backup={version:3,exported_at:new Date().toISOString(),source:sb?'Supabase + plaaslike kopie':'plaaslike kopie',data};
  const b=new Blob([JSON.stringify(backup,null,2)],{type:'application/json;charset=utf-8'});
  const u=URL.createObjectURL(b),a=document.createElement('a');
  a.href=u;a.download='WPU-2026-rugsteun.json';document.body.appendChild(a);a.click();a.remove();
  setTimeout(()=>URL.revokeObjectURL(u),1000);
  alert('Rugsteun afgelaai. Die rugsteun bevat nou die huidige Supabase-data en kan op ’n ander toestel herstel word.');
 }catch(e){alert('Rugsteun kon nie gemaak word nie: '+(e.message||e))}
}
async function restoreBackup(e){
 const f=e.target.files[0];if(!f)return;
 const r=new FileReader();
 r.onload=async()=>{
  try{
   const parsed=JSON.parse(r.result);
   const incoming=parsed&&parsed.data?parsed.data:parsed;
   if(!incoming||!Array.isArray(incoming.winners)||!Array.isArray(incoming.events)||!Array.isArray(incoming.results)||!Array.isArray(incoming.docs)||!incoming.info)throw new Error('Die rugsteunformaat is ongeldig.');
   if(sb&&!currentUser)throw new Error('Meld eers as Admin aan voordat jy ’n rugsteun na die wolk herstel.');
   data={winners:incoming.winners||[],events:incoming.events||[],results:incoming.results||[],docs:incoming.docs||[],info:incoming.info||{about:'',contacts:'',management:'',constitution:''}};
   if(sb){
    const cloudUpsert=async(table,row)=>{const {error}=await sb.from(table).upsert(row,{onConflict:'id'});if(error)throw error};
    for(const x of data.winners)await cloudUpsert('weekly_winners',{id:x.id,week:x.week,race:x.race,name:x.name,club:x.club||'',date:x.date||null,image_url:x.image||'',caption:x.caption||''});
    for(const x of data.events)await cloudUpsert('events',{id:x.id,title:x.title,date:x.date||null,location:x.location||'',description:x.description||'',images:x.images||[]});
    for(const x of data.results)await cloudUpsert('results',{id:x.id,title:x.title,category:x.category,date:x.date||null,pdf_url:x.url||''});
    for(const x of data.docs)await cloudUpsert('documents',{id:x.id,title:x.title,type:x.type,date:x.date||null,url:x.url||'',note:x.note||''});
    const {error:ie}=await sb.from('wpu_info').upsert({id:1,...data.info,updated_at:new Date().toISOString()},{onConflict:'id'});
    if(ie)throw ie;
    await cloudLoad();
   }
   save();render();alert('Rugsteun suksesvol herstel en met die wolk gesinkroniseer.');
  }catch(err){alert(err.message||'Ongeldige rugsteun.')}
  e.target.value='';
 };
 r.readAsText(f);
}
function resetDemo(){if(confirm('Herstel demo-inhoud? Jou huidige plaaslike data word vervang.')){localStorage.removeItem('wpu_data');data=seed;render()}}
async function refreshLive(){if(!sb)return;await cloudLoad();render()}
async function openPdf(url,title='PDF'){
 if(!url)return;
 try{
  if(url.startsWith('data:')){
   const parts=url.split(','),bin=atob(parts[1]||''),bytes=new Uint8Array(bin.length);
   for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);
   url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));
   setTimeout(()=>URL.revokeObjectURL(url),600000);
  }
  if(!/^https?:|^blob:/.test(url)){alert('Die PDF-skakel is ongeldig. Laai die PDF weer in by Admin.');return}
  const w=window.open(url,'_blank');
  if(!w){
   const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.click();
  }
 }catch(e){console.error(e);alert('Die PDF kon nie oopgemaak word nie. Tik “Open direk” om die foon se PDF-leser te gebruik.')}
} 
if(sb){sb.auth.getUser().then(({data:r})=>{currentUser=r.user||null;return cloudLoad()}).then(()=>render()).catch(()=>render())}else render(); if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{}); setInterval(()=>{if(sb)refreshLive().catch(()=>{})},60000);
